package field

import (
	"fmt"
	"strings"

	"github.com/maykel/gpg/entity"
	"github.com/maykel/gpg/generator/helpers"
)

func JSONFieldTemplate(f entity.Field, e entity.Entity, prefix *string) Template {
	name := f.Identifier
	if prefix != nil {
		name = fmt.Sprintf("%s_%s", *prefix, f.Identifier)
	}
	graphRequired := ""
	if f.Required {
		graphRequired = "!"
	}

	jsonMany := f.JSONConfig.Type == entity.ManyJSONConfigType
	fieldType := helpers.ToCamelCase(name)
	graphInTypeOptional := fmt.Sprintf("%s%sInput", helpers.ToCamelCase(e.Identifier), helpers.ToCamelCase(f.Identifier))
	graphOutType := fmt.Sprintf("%s%s", helpers.ToCamelCase(e.Identifier), helpers.ToCamelCase(f.Identifier))
	if jsonMany {
		fieldType = fmt.Sprintf("%sCollection", fieldType)
		graphInTypeOptional = fmt.Sprintf("[%s]", graphInTypeOptional)
		graphOutType = fmt.Sprintf("[%s]", graphOutType)
	}

	graphInType := fmt.Sprintf("%s%s", graphInTypeOptional, graphRequired)
	graphOutType = fmt.Sprintf("%s%s", graphOutType, graphRequired)

	if len(f.JSONConfig.Fields) == 0 {
		stringTemplate := StringFieldTemplate(f, e)
		stringTemplate.Type = "json.RawMessage"
		stringTemplate.GraphGenToMapper = fmt.Sprintf("StringFromJsonRaw(%s)", stringTemplate.GraphGenToMapper)
		stringTemplate.GraphGenFromMapper = strings.ReplaceAll(stringTemplate.GraphGenFromMapper, "StringFromPointer", "JsonRawFromString")
		stringTemplate.GraphGenFromMapperOptional = strings.ReplaceAll(stringTemplate.GraphGenFromMapperOptional, "StringFromPointer", "JsonRawFromString")
		return stringTemplate
	}

	return Template{
		Identifier:                 f.Identifier,
		Name:                       helpers.ToCamelCase(f.Identifier),
		Type:                       fieldType,
		IsPrimary:                  f.StorageConfig.PrimaryKey,
		Required:                   f.Required,
		Tags:                       helpers.ResolveTags(f),
		Import:                     nil,
		JSON:                       true,
		JSONMany:                   jsonMany,
		Custom:                     true,
		Generated:                  f.Autogenerated.Type != entity.InvalidAutogeneratedType,
		GeneratedFuncInsert:        resolveGeneratedFuncInsert(e, f),
		GeneratedFuncUpdate:        resolveGeneratedFuncUpdate(e, f),
		RepoToMapper:               fmt.Sprintf(".%sToJSON()", helpers.ToCamelCase(f.Identifier)),
		RepoFromMapper:             fmt.Sprintf("entity.%sFromJSON(model.%s)", helpers.ToCamelCase(f.Identifier), helpers.ToCamelCase(f.Identifier)),
		GraphName:                  f.Identifier,
		GraphModelName:             helpers.ToCamelCase(f.Identifier),
		GraphInType:                graphInType,
		GraphInTypeOptional:        graphInTypeOptional,
		GraphOutType:               graphOutType,
		GraphGenType:               fmt.Sprintf("%s%s", helpers.ToCamelCase(e.Identifier), helpers.ToCamelCase(f.Identifier)),
		GraphGenToMapper:           fmt.Sprintf("Map%s%s(i.%s)", helpers.ToCamelCase(e.Identifier), helpers.ToCamelCase(f.Identifier), helpers.ToCamelCase(f.Identifier)),
		GraphGenFromMapperParam:    "",
		GraphGenFromMapper:         fmt.Sprintf("Map%s%sInput(i.%s)", helpers.ToCamelCase(e.Identifier), helpers.ToCamelCase(f.Identifier), helpers.ToCamelCase(f.Identifier)),
		GraphGenFromMapperOptional: fmt.Sprintf("Map%s%sInput(i.%s)", helpers.ToCamelCase(e.Identifier), helpers.ToCamelCase(f.Identifier), helpers.ToCamelCase(f.Identifier)),
	}
}
